name: Build and Deploy
on:
  push:
    branches:
      - master  # Set a branch to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install and Build 
      run: |
        npm install
        npm run build  # Replace with your build command

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Replace with your directory
